import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles//globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-1/2 md:w-full h-3/5 border-dotted border-2 border-red-400">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
